// import type { ExhibitionTableRow } from './ExhibitionsTable'
// import { Works } from '@/src/types/works'

// export const ExhibitionData: ExhibitionTableRow[] = [
//   {
//     work: Works.deviation_game,
//     exhibition_name: 'PARCO POND 2023',
//     city: 'Tokyo, Japan',
//     place: 'Parco Shibuya',
//     date: '2023.11.17 - 12.4',
//   },
//   {
//     work: Works.deviation_game,
//     exhibition_name: 'Now Play This 2023',
//     city: 'London, UK',
//     place: 'V&A Museum',
//     date: '2023.04.01 - 04.09',
//   },
//   {
//     work: Works.deviation_game,
//     exhibition_name: 'Cinekid Festival 2023',
//     city: 'Amsterdam, Netherlands',
//     place: 'Cinekid Festival',
//     date: '2023.10.14 - 10.29',
//   },
//   {
//     work: Works.deviation_game,
//     exhibition_name: 'Ars Electronica Festival 2023',
//     city: 'Linz, Austria',
//     place: 'Post City',
//     date: '2023.09.06 - 09.10',
//   },
//   {
//     work: Works.deviation_game,
//     exhibition_name: 'CCBT Fellowship 2023',
//     city: 'Tokyo, Japan',
//     place: 'CCBT',
//     date: '2023.03.04 - 03.26',
//   },
//   {
//     work: 'Synthetic Feather',
//     exhibition_name: 'Synthetic Feather - Art & New Ecology',
//     city: 'Tokyo, Japan',
//     place: 'The University Art Museum',
//     date: '2022.05.28 - 06.26',
//   },
//   {
//     work: Works.morphing_identity,
//     exhibition_name: 'You and Robots, What is it to be Human?',
//     city: 'Tokyo, Japan',
//     place: 'The National Museum of Emerging Science and Innovation (Miraikan)',
//     date: '2022.3.18 - 8.31',
//   },
//   {
//     work: 'Xenon',
//     exhibition_name: 'Year 2121 , Futures In-Sight',
//     city: 'Tokyo, Japan',
//     place: '21_21 Design Sight',
//     date: '2021.12.21 - 05.22',
//   },
//   {
//     work: Works.morphing_identity,
//     exhibition_name: 'Research for the Future of Humanity',
//     city: 'Tokyo, Japan',
//     place: 'Sony Park Exhibition',
//     date: '2021.07 - 2021.08',
//   },
//   {
//     work: 'Double Horizon',
//     exhibition_name: 'Paper and Me Festival',
//     city: 'Kochi, Japan',
//     place: 'Ino Town Paper Museum',
//     date: '2021.10.01 - 10.17',
//   },
//   {
//     work: 'Double Horizon',
//     exhibition_name: 'Alternative Kyoto - Artspace of the Light',
//     city: 'Kyoto, Japan',
//     place: 'Amanohashidate',
//     date: '2020.10.16 - 11.23',
//   },
//   {
//     work: 'Xenon',
//     exhibition_name: 'Histopolis - Extinction and Regeneration',
//     city: 'Tokyo, Japan',
//     place: 'Gyre Gallery',
//     date: '2020.06.08 - 09.27',
//   },
//   {
//     work: 'Aubik',
//     exhibition_name: 'Making Fashion Sense',
//     city: 'Basel, Switzerland',
//     place: 'Haus der elektronischen Kunste Basel (HeK)',
//     date: '2020.01 - 2020.03',
//   },
//   {
//     work: 'Aubik',
//     exhibition_name: 'Histopolis - Extinction and Regeneration',
//     city: 'Tokyo, Japan',
//     place: 'Gyre Gallery',
//     date: '2020.06 - 2020.09',
//   },
//   {
//     work: Works.algorithmic_couture,
//     exhibition_name: 'AnyTokyo Japan',
//     city: 'Tokyo, Japan',
//     place: 'Kudanhouse',
//     date: '2019.11.15 - 11.24',
//   },
//   {
//     work: 'Aubik',
//     exhibition_name: 'FIVE PASSAGES TO THE FUTURE',
//     city: 'Jakarta, Indonesia',
//     place: 'Galeri Nasional Indonesia',
//     date: '2019.10.21 - 11.07',
//   },
//   {
//     work: Works.algorithmic_couture,
//     exhibition_name: 'Keio SFC Open Research Forum',
//     city: 'Tokyo, Japan',
//     place: 'Roppongi Midtown',
//     date: '2018.11.22 - 11.23',
//   },
//   {
//     work: 'Harmonize',
//     exhibition_name: 'Yuima Nakazato',
//     city: 'Tokyo, Japan',
//     place: '2121 Design Sight',
//     date: '2018.02.21 - 02.25',
//   },
// ]
